application: electricpeach25
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /scripts
  static_dir: scripts
  
- url: /images
  static_dir: images
  
- url: /utilities
  static_dir: utilities

- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"